spring.application.name=url-shortener

spring.datasource.url=jdbc:postgresql://localhost:5432/url-shortener
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mysupersecretkeyforjwtauthentication2026springbootproject
jwt.expirationMs=86400000

logging.level.org.springframework.security=DEBUG